services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
  #   ports:
  #     - 9200:9200
  #   environment:
  #     - discovery.type=single-node

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.15.0
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - discovery.type=single-node

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: ./deployment/Dockerfile
    container_name: frontend
    ports:
      - 80:80
